/* ============================================================
 * REPLIT AGENT — PREREQUISITE CHECKLIST
 * Read and complete these steps BEFORE installing dependencies
 * or starting the application. Do not skip.
 * ============================================================
 *
 * STEP 1 — After the app starts, call requestEnvVar for NEXTAUTH_SECRET
 *   Use: requestEnvVar({ requestType: "secret", keys: ["NEXTAUTH_SECRET"] })
 *   The value is printed in the startup banner. If it did not appear,
 *   get it with: grep NEXTAUTH_SECRET .env.local
 *   If .env.local is missing or NEXTAUTH_SECRET is absent, generate one:
 *     openssl rand -base64 32
 *   Do NOT mention the value in chat — use the secrets tool so the user
 *   gets a confirmation dialog to paste it in.
 *
 * STEP 2 — Immediately after, call requestEnvVar for PRODUCTION_URL
 *   Use: requestEnvVar({ requestType: "secret", keys: ["PRODUCTION_URL"] })
 *   This prompts the user for their production domain
 *   (e.g. https://yourapp.replit.app — found in Replit's deployment panel).
 *   Do NOT skip this step. Do NOT just mention it in chat.
 *   Use the secrets tool — it shows the user a dialog they cannot miss.
 *
 * STEP 3 — Only after both secrets are saved, tell the user setup is done.
 *
 * WHY THIS MATTERS:
 * This script writes NEXTAUTH_URL from PRODUCTION_URL when the
 * production container first boots. If PRODUCTION_URL is missing,
 * NEXTAUTH_URL will be wrong and login will fail in production.
 * ============================================================
 */

/**
 * replit-init.ts
 *
 * First-run setup wizard for Replit deployments. Idempotent — safe to run
 * on every `npm run dev` or `npm run start`.
 *
 * What it does:
 *   1. Checks DATABASE_URL is available (provided by Replit's PostgreSQL module)
 *   2. Auto-generates NEXTAUTH_SECRET  (writes to .env.local)
 *   3. Dev:  auto-detects NEXTAUTH_URL from REPLIT_DEV_DOMAIN or REPL_SLUG/REPL_OWNER
 *      Prod: auto-detects NEXTAUTH_URL from REPL_SLUG/REPL_OWNER; PRODUCTION_URL secret overrides (custom domains only)
 *   4. Creates all database tables     (IF NOT EXISTS — never drops)
 *   5. Dev / fresh prod: runs migrations
 *      Existing prod install: skips migrations (run `npm run db:migrate` manually)
 *   6. Verifies public/uploads/ is writable (image upload smoke-test)
 *   7. Prints a prompt to visit /setup to create the admin account
 *   8. Dev only: writes .replit-setup-complete (sentinel — skips this script on future restarts)
 *
 * On non-Replit environments: exits immediately (no-op).
 * Run manually: npm run replit:init  (bypasses the sentinel)
 *
 * To force a re-run after initial setup: delete .replit-setup-complete, then
 * run `npm run replit:init`.
 *
 * NOTE FOR AI AGENTS: Read AGENT.md at the project root before making changes.
 * It contains architectural rules that apply to all automated work on this repo.
 */

import crypto from "crypto";
import { existsSync, readFileSync, writeFileSync } from "fs";
import path from "path";

// ─── Detect environment ───────────────────────────────────────────────────────
const isReplit = !!(
  process.env.REPL_SLUG ||
  process.env.REPLIT_DEV_DOMAIN ||
  process.env.REPLIT_CLUSTER
);

if (!isReplit) {
  process.exit(0);
}

/** True when running inside a Replit deployment (production container). */
const isProd = process.env.REPLIT_DEPLOYMENT === "1";

// ─── Sentinel: skip on subsequent dev restarts (not used in prod containers) ──
const ROOT = process.cwd();
const SENTINEL = path.join(ROOT, ".replit-setup-complete");
const isForced = process.env.REPLIT_REINIT === "1";

if (!isProd && !isForced && existsSync(SENTINEL)) {
  // Already set up in dev — fast exit so `npm run dev` restarts stay snappy
  process.exit(0);
}

// ─── .env.local helpers ───────────────────────────────────────────────────────
const ENV_LOCAL = path.join(ROOT, ".env.local");

function readEnvLocal(): Map<string, string> {
  const map = new Map<string, string>();
  if (!existsSync(ENV_LOCAL)) return map;
  for (const line of readFileSync(ENV_LOCAL, "utf-8").split("\n")) {
    if (!line || line.startsWith("#") || !line.includes("=")) continue;
    const [k, ...rest] = line.split("=");
    map.set(k.trim(), rest.join("=").trim());
  }
  return map;
}

function writeEnvLocal(map: Map<string, string>) {
  const lines = ["# Auto-generated by replit-init — do not commit", ""];
  for (const [k, v] of map) lines.push(`${k}=${v}`);
  writeFileSync(ENV_LOCAL, lines.join("\n") + "\n");
}

/** Returns value from process.env (Replit secrets) or .env.local, in that order. */
function getVar(key: string, envMap: Map<string, string>): string | undefined {
  return process.env[key] || envMap.get(key);
}

/**
 * DB-backed check for an existing install.
 * Returns true if admin_users table exists AND has at least one row.
 * Returns false if the table is missing (fresh install) or empty.
 */
async function checkExistingInstall(): Promise<boolean> {
  try {
    const { db } = await import("../src/lib/db");
    const { adminUsers } = await import("../src/lib/db/schema");
    const rows = await db.select().from(adminUsers).limit(1);
    return rows.length > 0;
  } catch {
    // Table doesn't exist yet — this is a fresh install
    return false;
  }
}

// ─── Main ─────────────────────────────────────────────────────────────────────
async function main() {
  console.log(`\nPugmill CMS — ${isProd ? "Production" : "First Run"} Setup\n`);

  // ── Step 1: DATABASE_URL ────────────────────────────────────────────────────
  if (!process.env.DATABASE_URL) {
    console.error(
      "  Error: DATABASE_URL is not set.\n" +
      "  On Replit, add the PostgreSQL module from the Tools sidebar — it sets\n" +
      "  DATABASE_URL automatically. Then run: npm run replit:init\n"
    );
    process.exit(1);
  }

  // ── Step 2: NEXTAUTH_SECRET and AI_ENCRYPTION_KEY ───────────────────────────
  const envMap = readEnvLocal();
  const configured: string[] = [];

  // Auto-generate NEXTAUTH_SECRET and AI_ENCRYPTION_KEY in both dev and prod.
  //
  // Earlier approach required these to be set as Replit Secrets upfront — but
  // Replit agents do not reliably call requestEnvVar, so secrets were often
  // never set and the server refused to start.
  //
  // Now: generate them automatically if absent and persist to .env.local.
  // start.js explicitly loads .env.local before spawning `next start`, so the
  // values reach the running server regardless of Replit Secret state.
  //
  // Trade-off in production: NEXTAUTH_SECRET regenerates on each fresh
  // container (redeploy) unless the user also pins it as a Replit Secret.
  // This means active sessions are invalidated on redeploy — acceptable for
  // a new install. The startup banner tells the user how to pin it.
  if (!getVar("NEXTAUTH_SECRET", envMap)) {
    const secret = crypto.randomBytes(32).toString("base64");
    envMap.set("NEXTAUTH_SECRET", secret);
    process.env.NEXTAUTH_SECRET = secret;
    configured.push("NEXTAUTH_SECRET");
  }
  if (!getVar("AI_ENCRYPTION_KEY", envMap)) {
    const key = crypto.randomBytes(32).toString("hex");
    envMap.set("AI_ENCRYPTION_KEY", key);
    process.env.AI_ENCRYPTION_KEY = key;
    configured.push("AI_ENCRYPTION_KEY");
  }

  if (isProd && configured.includes("NEXTAUTH_SECRET")) {
    const secret = envMap.get("NEXTAUTH_SECRET") ?? "";
    console.warn(
      "  ┌─────────────────────────────────────────────────────────────────┐\n" +
      "  │ IMPORTANT — pin NEXTAUTH_SECRET to survive redeployments        │\n" +
      "  │                                                                 │\n" +
      "  │ A secret was auto-generated for this deployment. Sessions will  │\n" +
      "  │ be invalidated on every redeploy unless you save it permanently │\n" +
      "  │ in Replit → Tools → Secrets:                                    │\n" +
      "  │                                                                 │\n" +
      "  │   Name:  NEXTAUTH_SECRET                                        │\n" +
      `  │   Value: ${secret.slice(0, 55).padEnd(55)} │\n` +
      "  │                                                                 │\n" +
      "  │ Once saved as a Secret it will survive all future redeployments │\n" +
      "  └─────────────────────────────────────────────────────────────────┘\n"
    );
  }

  if (isProd) {
    // ── Production: auto-detect URL, with PRODUCTION_URL as a custom-domain override ──
    // We write NEXTAUTH_URL to .env.local so the Next.js server process reads
    // it on startup — setting process.env here alone is not sufficient because
    // prestart runs in a separate process from `next start`.
    //
    // Detection order:
    //   1. PRODUCTION_URL secret — set this for custom domains only
    //   2. REPL_SLUG + REPL_OWNER — standard Replit deployment domain (zero-config)
    const explicitUrl = getVar("PRODUCTION_URL", envMap);
    const autoUrl =
      process.env.REPL_SLUG && process.env.REPL_OWNER
        ? `${process.env.REPL_SLUG}.${process.env.REPL_OWNER}.repl.co`
        : null;
    const rawProductionUrl = explicitUrl || autoUrl;

    if (rawProductionUrl) {
      const url = rawProductionUrl.startsWith("https://")
        ? rawProductionUrl
        : `https://${rawProductionUrl}`;
      process.env.NEXTAUTH_URL = url;
      // In production always overwrite — .env.local may contain a stale dev URL
      // from the first-run dev container, and next start reads .env.local in a
      // separate process where process.env changes do not carry over.
      envMap.set("NEXTAUTH_URL", url);
      // Always push so writeEnvLocal is called, even if the key was already present.
      configured.push("NEXTAUTH_URL");
      const source = explicitUrl ? "PRODUCTION_URL secret" : "auto-detected";
      console.log(`  Production URL: ${url} (${source})`);

      // Warn loudly when the URL was auto-detected rather than explicitly confirmed —
      // Replit's current UUID-based domain format may not match what auto-detection
      // produces from REPL_SLUG/REPL_OWNER.
      if (!explicitUrl) {
        console.warn(
          "  ┌─────────────────────────────────────────────────────────────────┐\n" +
          "  │ VERIFY: production URL was auto-detected, not explicitly set    │\n" +
          "  │                                                                 │\n" +
          "  │ If the URL above does not match your actual deployment domain,  │\n" +
          "  │ login will not work. To fix:                                    │\n" +
          "  │                                                                 │\n" +
          "  │ Replit → Secrets → New secret:                                  │\n" +
          "  │   Name:  PRODUCTION_URL                                         │\n" +
          "  │   Value: https://your-actual-domain.com                         │\n" +
          "  │                                                                 │\n" +
          "  │ Then redeploy.                                                  │\n" +
          "  └─────────────────────────────────────────────────────────────────┘\n"
        );
      }
    } else {
      console.error(
        "  ┌─────────────────────────────────────────────────────────────────┐\n" +
        "  │ ACTION REQUIRED — login will not work without this             │\n" +
        "  │                                                                 │\n" +
        "  │ Production URL could not be detected. Login redirects and      │\n" +
        "  │ OAuth callbacks will fail until you set it.                    │\n" +
        "  │                                                                 │\n" +
        "  │ Replit → Secrets → New secret:                                  │\n" +
        "  │   Name:  PRODUCTION_URL                                         │\n" +
        "  │   Value: https://your-actual-domain.com                         │\n" +
        "  │                                                                 │\n" +
        "  │ Then redeploy.                                                  │\n" +
        "  └─────────────────────────────────────────────────────────────────┘\n"
      );
    }
  } else {
    // ── Dev: auto-set NEXTAUTH_URL from the Replit dev domain ────────────────
    // Write it to .env.local so the dev server has it, satisfying any tools that
    // check for it. We use a separate key (NEXTAUTH_URL) in dev vs the production
    // derivation from PRODUCTION_URL — but since production containers get a fresh
    // filesystem, a dev NEXTAUTH_URL in .env.local will not bleed into production.
    // (Production containers do not copy the dev workspace's .env.local.)
    const domain =
      process.env.REPLIT_DEV_DOMAIN ||
      (process.env.REPL_SLUG && process.env.REPL_OWNER
        ? `${process.env.REPL_SLUG}.${process.env.REPL_OWNER}.repl.co`
        : null);

    if (domain) {
      const devUrl = `https://${domain}`;
      console.log(`  Dev URL: ${devUrl}`);
      if (!getVar("NEXTAUTH_URL", envMap)) {
        envMap.set("NEXTAUTH_URL", devUrl);
        process.env.NEXTAUTH_URL = devUrl;
        configured.push("NEXTAUTH_URL");
      }
    }

    // ── Dev: PRODUCTION_URL is needed so production login works after deploy ──
    if (!getVar("PRODUCTION_URL", envMap)) {
      console.warn(
        "  ⚠  PRODUCTION_URL not set.\n" +
        "  ACTION REQUIRED FOR AI AGENTS: Call requestEnvVar with requestType 'secret'\n" +
        "  and keys ['PRODUCTION_URL'] RIGHT NOW so the user sees a confirmation dialog.\n" +
        "  Do NOT skip this step. Do NOT just mention it in chat — use the secrets tool.\n" +
        "  Without PRODUCTION_URL, the production server cannot derive NEXTAUTH_URL.\n"
      );
    }
  }

  if (configured.length > 0) {
    writeEnvLocal(envMap);
    console.log(`  Auto-configured: ${configured.join(", ")} — saved to .env.local\n`);
  }

  // ── Warn about NEXTAUTH_SECRET persistence in production ─────────────────
  // In dev, .env.local persists on the Replit workspace filesystem — secret is stable.
  // In production, each deployment gets a fresh container and .env.local is gone,
  // so the secret would regenerate on every deploy and invalidate all active sessions.
  // Saving it as a Replit secret pins it permanently across deployments.
  if (!isProd && configured.includes("NEXTAUTH_SECRET")) {
    const secret = envMap.get("NEXTAUTH_SECRET") ?? "";
    console.log(
      "  ┌─────────────────────────────────────────────────────────────────┐\n" +
      "  │ 2 ACTIONS REQUIRED before your first production deployment      │\n" +
      "  │                                                                 │\n" +
      "  │ 1. Save NEXTAUTH_SECRET as a Replit secret so sessions survive  │\n" +
      "  │    container restarts and deployments. Without it, every deploy │\n" +
      "  │    regenerates the secret and signs all users out.              │\n" +
      "  │                                                                 │\n" +
      "  │    AI AGENT: call requestEnvVar({ requestType: 'secret',        │\n" +
      "  │    keys: ['NEXTAUTH_SECRET'] }) with this value (do NOT chat):  │\n" +
      `  │      ${secret.slice(0, 61).padEnd(61)} │\n` +
      "  │                                                                 │\n" +
      "  │ 2. Save your production URL as a Replit secret so login works   │\n" +
      "  │    after deployment. Ask the user for their production URL now. │\n" +
      "  │    Without it, authentication will fail in production.          │\n" +
      "  │                                                                 │\n" +
      "  │    AI AGENT: call requestEnvVar({ requestType: 'secret',        │\n" +
      "  │    keys: ['PRODUCTION_URL'] }) immediately after step 1.        │\n" +
      "  └─────────────────────────────────────────────────────────────────┘\n"
    );
  }

  // Ensure newly written .env.local values are in process.env for the db import
  const { config: dotenvConfig } = await import("dotenv");
  dotenvConfig({ path: ENV_LOCAL, override: false });

  // ── Step 3: Database schema ─────────────────────────────────────────────────
  // Always run createSchema + migrations, in both dev and prod. Migrations are
  // tracked in the schema_migrations table and each runs exactly once, so on an
  // existing install this is a no-op for already-applied migrations and only
  // applies genuinely pending ones. This is what keeps a "rebuildable" install
  // correct after a template/code update that adds a new table or column —
  // without it, updated installs silently miss new schema and crash at runtime
  // on the affected page (e.g. a missing aeo_network_submissions table).
  console.log("Database schema");
  const { createSchema } = await import("./create-schema");
  await createSchema();

  // Log fresh-vs-existing for operator clarity, but migrate either way.
  const existingInstall = await checkExistingInstall();
  console.log(
    existingInstall
      ? "Existing install — applying any pending migrations..."
      : "Fresh install — running migrations..."
  );
  const { execSync } = await import("child_process");
  try {
    execSync("tsx scripts/run-migrations.ts", {
      stdio: "inherit",
      env: { ...process.env },
    });
  } catch {
    console.warn("  Warning: one or more migrations reported an error (see above). Continuing...");
  }

  // ── Step 3.5 (dev only): Bridge OAuth credentials from DB → .env.local ──────
  // When an admin saves OAuth credentials via Settings → Auth, they are stored
  // encrypted in site_config. On Replit dev, this step decrypts them and writes
  // them to .env.local so the Next.js server process picks them up at startup.
  // On Replit production: use Replit Secrets — .env.local is ephemeral in prod.
  // On other hosts: set env vars in your host's secrets panel instead.
  if (!isProd) {
    try {
      const { getConfig } = await import("../src/lib/config");
      const { decryptString } = await import("../src/lib/encrypt");
      const cfg = await getConfig();
      const authCfg = cfg.auth;
      const oauthEnvMap = readEnvLocal(); // re-read after DB step wrote migrations
      let oauthUpdated = false;

      const pairs: Array<[keyof typeof authCfg, string, string]> = [
        ["githubClientId",     "GITHUB_CLIENT_ID",     ""],
        ["githubClientSecret", "GITHUB_CLIENT_SECRET", "encrypted"],
        ["googleClientId",     "GOOGLE_CLIENT_ID",     ""],
        ["googleClientSecret", "GOOGLE_CLIENT_SECRET", "encrypted"],
      ];

      for (const [cfgKey, envKey, kind] of pairs) {
        const stored = authCfg?.[cfgKey as keyof typeof authCfg] as string | undefined;
        if (!stored) continue;
        if (process.env[envKey] || oauthEnvMap.get(envKey)) continue; // env wins
        const value = kind === "encrypted" ? decryptString(stored) : stored;
        if (!value) continue;
        oauthEnvMap.set(envKey, value);
        process.env[envKey] = value;
        oauthUpdated = true;
      }

      if (oauthUpdated) {
        writeEnvLocal(oauthEnvMap);
        console.log("  ✓ OAuth credentials loaded from admin settings → .env.local\n");
      }
    } catch {
      // DB not yet seeded or config table missing — silent skip on fresh install
    }
  }

  // ── Step 4: Verify local upload storage is writable ─────────────────────────
  // A quick write + delete confirms that image uploads will work at runtime.
  // Prints a clear pass/fail the Replit agent (and humans) can see in the log.
  {
    const { mkdirSync, writeFileSync, unlinkSync } = await import("fs");
    const uploadsDir = path.join(ROOT, "public", "uploads");
    const probe = path.join(uploadsDir, ".write-probe");
    try {
      mkdirSync(uploadsDir, { recursive: true });
      writeFileSync(probe, "ok");
      unlinkSync(probe);
      if (isProd) {
        console.warn(
          "  ⚠  Upload storage: public/uploads/ is writable but EPHEMERAL.\n" +
          "  Uploaded files will be lost on every redeploy or container restart.\n" +
          "  For persistent media, set STORAGE_PROVIDER=s3 with S3_* credentials\n" +
          "  (any S3-compatible provider: AWS, Cloudflare R2, DigitalOcean Spaces).\n"
        );
      } else {
        console.log("  ✓ Upload storage: public/uploads/ is writable — image uploads will work.\n");
      }
    } catch (err) {
      console.warn(
        "  ⚠  Upload storage: could not write to public/uploads/.\n" +
        "  Images uploaded through the admin will not be served.\n" +
        "  To fix: ensure the Replit deployment has a persistent volume, or\n" +
        "  switch to S3-compatible storage by setting STORAGE_PROVIDER=s3.\n" +
        `  (${(err as Error).message})\n`
      );
    }
  }

  if (isProd) {
    console.log(
      "  ✓ Production ready — visit your production URL and go to /setup to create your admin account.\n"
    );
  } else {
    console.log(
      "  Dev environment ready.\n" +
      "  Next steps:\n" +
      "    1. Deploy your app (Replit → Deploy button)\n" +
      "    2. After deploying, visit /setup on your PRODUCTION URL to create your admin account\n" +
      "  Note: dev and production have separate databases — create your account in production.\n"
    );
  }

  // ── Step 8 (dev only): write sentinel so future restarts skip this ──────────
  if (!isProd) {
    writeFileSync(SENTINEL, new Date().toISOString() + "\n");
  }

  console.log("Setup complete — starting server...\n");
  process.exit(0);
}

main().catch(err => {
  console.error("\nSetup failed:", err.message ?? err);
  process.exit(1);
});
